# Generated by Django 4.2.11 on 2024-09-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0003_user_token_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameType',
        ),
    ]
