# Generated by Django 4.2.11 on 2024-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0005_playerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'db_table': 'FutureStar_App_UserPost',
            },
        ),
    ]
