# Generated by Django 4.2.11 on 2024-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0006_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
