# Generated by Django 4.2.11 on 2024-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0010_playerbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('team_A', models.CharField(max_length=255)),
                ('team_B', models.CharField(max_length=255)),
                ('game_field', models.CharField(max_length=255)),
                ('referee_name', models.CharField(max_length=255)),
            ],
        ),
    ]
