# Generated by Django 4.2.11 on 2024-09-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0011_friendlygame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('Phone_Number', models.PositiveIntegerField(default='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('main_playing_position', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_playing_position', models.CharField(blank=True, max_length=50, null=True)),
                ('playing_foot', models.CharField(blank=True, max_length=10, null=True)),
                ('favourite_local_team', models.CharField(blank=True, max_length=100, null=True)),
                ('favourite_team', models.CharField(blank=True, max_length=100, null=True)),
                ('favourite_local_player', models.CharField(blank=True, max_length=100, null=True)),
                ('favourite_player', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
