# Generated by Django 5.0 on 2024-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
