# Generated by Django 5.1.1 on 2024-09-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0004_editstuff_friendlygame_player_profile_playerbranch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditStuff',
        ),
        migrations.DeleteModel(
            name='FriendlyGame',
        ),
        migrations.DeleteModel(
            name='GameType',
        ),
        migrations.DeleteModel(
            name='PlayerBranch',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.AddField(
            model_name='player_profile',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
