# Generated by Django 5.0 on 2024-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0005_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='global_clients/')),
            ],
        ),
    ]
