# Generated by Django 5.0 on 2024-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0006_global_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tryout_Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tryout_club/')),
            ],
        ),
    ]
