# Generated by Django 5.0 on 2024-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0008_inquire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
                ('content', models.TextField()),
                ('rattings', models.CharField(max_length=5)),
            ],
        ),
    ]
