# Generated by Django 5.0 on 2024-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0009_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='app_rate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='downloads',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='happy_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='line_of_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
