# Generated by Django 5.0 on 2024-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0010_systemsettings_app_rate_systemsettings_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='awards_winning',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='proffesioan_team_members',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='project_completed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
