# Generated by Django 4.2.11 on 2024-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0011_systemsettings_awards_winning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Title_content', models.CharField(blank=True, max_length=1000)),
                ('Title_background', models.TextField(blank=True, max_length=255)),
                ('contact_us', models.CharField(blank=True, max_length=255)),
                ('contact_us_title', models.CharField(blank=True, max_length=255)),
                ('contact_country', models.CharField(blank=True, max_length=255)),
                ('contact_mail_icon', models.TextField(blank=True, max_length=255)),
                ('contact_phone_icon', models.TextField(blank=True, max_length=255)),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('quote_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'ContactPage',
            },
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designations', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/')),
                ('news_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
