# Generated by Django 4.2.11 on 2024-09-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FutureStar_App', '0012_contactpage_team_members'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactpage',
            table=None,
        ),
    ]
